//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Online_Exams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public string Chc_Id { get; set; }
        public int Qstn_Id { get; set; }
        public string Chc_Text { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
