//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Online_Exams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.Exam_Question = new HashSet<Exam_Question>();
        }
    
        public int Exam_Id { get; set; }
        public int St_Id { get; set; }
        public int Crs_Id { get; set; }
        public Nullable<int> Exam_Grade { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Exam_Question> Exam_Question { get; set; }
    }
}
