//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Online_Exams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Choices = new HashSet<Choice>();
            this.Exam_Question = new HashSet<Exam_Question>();
        }
    
        public int Qstn_Id { get; set; }
        public string Qstn_Text { get; set; }
        public string Qstn_Type { get; set; }
        public string Qstn_Answer { get; set; }
        public int Crs_Id { get; set; }
    
        public virtual ICollection<Choice> Choices { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<Exam_Question> Exam_Question { get; set; }
    }
}
