<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="StudentHome.aspx.cs" Inherits="ITI_Online_Exams.StudentHome" %>
<asp:Content ID="Content1" ContentPlaceHolderID="navPlaceHolder" runat="server">
    <li><a href="#" id="current" accesskey="h">Home</a></li>
    <li><a href="#" accesskey="e">Exams</a></li>
    <li><a href="#" accesskey="g">Grade</a></li>
    <li><a href="#" accesskey="c">Courses</a></li>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="headerPlaceHolder1" runat="server">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sem urna, fermentum interdum consectetur vitae, dignissim vitae ipsum. Suspendisse tincidunt eget tortor eget vehicula. In finibus dui id convallis gravida. Suspendisse mauris magna, dapibus eget eros id, faucibus porttitor ex. Nullam dictum mollis lorem id pharetra. Morbi facilisis eu nibh non accumsan. Nulla bibendum convallis velit a bibendum. Praesent fringilla dui ut posuere pellentesque. Praesent commodo, nunc sit amet suscipit convallis, mi tortor tristique orci, at sagittis lorem dui at sapien. Vestibulum nec elementum ante. Ut placerat mauris eget velit laoreet luctus. Praesent vitae orci sed neque condimentum vehicula. Fusce sit amet tortor enim. Ut leo metus, cursus nec nibh eu, molestie iaculis sem. Mauris facilisis nunc sed ligula bibendum, at egestas nulla tempus. Nullam egestas bibendum arcu, et vehicula ante porta quis.

Praesent ac mi nec lectus luctus iaculis vitae id arcu. Nam vel dolor ac orci ornare lobortis. Sed fringilla massa sit amet ligula fermentum ultrices. Nunc vitae odio a neque feugiat convallis et in dolor. Nulla ornare nisl in tortor pretium feugiat. Vivamus egestas diam ut felis condimentum, nec vulputate quam venenatis. Vestibulum lacinia dui eu mollis scelerisque. Nullam quis purus eget mi ullamcorper euismod.
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sem urna, fermentum interdum consectetur vitae, dignissim vitae ipsum. Suspendisse tincidunt eget tortor eget vehicula. In finibus dui id convallis gravida. Suspendisse mauris magna, dapibus eget eros id, faucibus porttitor ex. Nullam dictum mollis lorem id pharetra. Morbi facilisis eu nibh non accumsan. Nulla bibendum convallis velit a bibendum. Praesent fringilla dui ut posuere pellentesque. Praesent commodo, nunc sit amet suscipit convallis, mi tortor tristique orci, at sagittis lorem dui at sapien. Vestibulum nec elementum ante. Ut placerat mauris eget velit laoreet luctus. Praesent vitae orci sed neque condimentum vehicula. Fusce sit amet tortor enim. Ut leo metus, cursus nec nibh eu, molestie iaculis sem. Mauris facilisis nunc sed ligula bibendum, at egestas nulla tempus. Nullam egestas bibendum arcu, et vehicula ante porta quis.

Praesent ac mi nec lectus luctus iaculis vitae id arcu. Nam vel dolor ac orci ornare lobortis. Sed fringilla massa sit amet ligula fermentum ultrices. Nunc vitae odio a neque feugiat convallis et in dolor. Nulla ornare nisl in tortor pretium feugiat. Vivamus egestas diam ut felis condimentum, nec vulputate quam venenatis. Vestibulum lacinia dui eu mollis scelerisque. Nullam quis purus eget mi ullamcorper euismod.
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="extracontentPlaceHolder" runat="server">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sem urna, fermentum interdum consectetur vitae, dignissim vitae ipsum. Suspendisse tincidunt eget tortor eget vehicula. In finibus dui id convallis gravida. Suspendisse mauris magna, dapibus eget eros id, faucibus porttitor ex. Nullam dictum mollis lorem id pharetra. Morbi facilisis eu nibh non accumsan. Nulla bibendum convallis velit a bibendum. Praesent fringilla dui ut posuere pellentesque. Praesent commodo, nunc sit amet suscipit convallis, mi tortor tristique orci, at sagittis lorem dui at sapien. Vestibulum nec elementum ante. Ut placerat mauris eget velit laoreet luctus. Praesent vitae orci sed neque condimentum vehicula. Fusce sit amet tortor enim. Ut leo metus, cursus nec nibh eu, molestie iaculis sem. Mauris facilisis nunc sed ligula bibendum, at egestas nulla tempus. Nullam egestas bibendum arcu, et vehicula ante porta quis.

Praesent ac mi nec lectus luctus iaculis vitae id arcu. Nam vel dolor ac orci ornare lobortis. Sed fringilla massa sit amet ligula fermentum ultrices. Nunc vitae odio a neque feugiat convallis et in dolor. Nulla ornare nisl in tortor pretium feugiat. Vivamus egestas diam ut felis condimentum, nec vulputate quam venenatis. Vestibulum lacinia dui eu mollis scelerisque. Nullam quis purus eget mi ullamcorper euismod.
</asp:Content>
