//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Online_Exams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int Top_Id { get; set; }
        public string Top_Name { get; set; }
        public int Crs_Id { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
